### ISSUE TITLE
npy download links are down

### ISSUE THREAD

**Issue by sepideh-srj** [Time0o/colorful-colorization#41]
Hi, 
I think the links to the ab-gamut.npy and q-prior.npy are down. 
Can you provide it again?

**Comment by Time0o** [comment]
I think those links have just moved to the `caffe` branch in `https://github.com/richzhang/colorization`, it would probably make more sense to change the links in `get_resources.sh` to point to some specific commit in that repo. You could create a pull request for that if you want (or just download the files from [here](https://github.com/richzhang/colorization/tree/caffe/resources) for now).

**Comment by sepideh-srj** [comment]
Thank you, the links are working fine now, but now I'm getting an error for reading them!

OSError: Failed to interpret file 'resources/ab-gamut.npy' as a pickle

Here is where the error occurs: 
        self.points = np.load(self.RESOURCE_POINTS, allow_pickle=True).astype(self.DTYPE)

I tried to set allow_picke=True but it also didn't solve the issue. 
Can you help me with it?

Thanks

**Comment by Time0o** [comment]
Did you download the files using the most recent commit I've pushed to master? Someone else had the same problem and I've encountered it too but with the updated links it should work. E.g. for me it works with numpy version 1.20.1, with or without `allow_pickle=True`.

**Comment by sepideh-srj** [comment]
Thank you, the issue is solved now.
